### ISSUE TITLE
Issues with integer division 

### ISSUE THREAD

**Issue by SergioRAgostinho** [dylan-campbell/bpnpnet#2]
Hey Dylan,

I'm not really sure if you intend to support Python 3, but I just wanted to bring to your attention that this expectation on the integer division no longer holds in Python 3. You need to use the operator `//`.
https://github.com/dylan-campbell/bpnpnet/blob/21642c830c0544cd71ddb1c02873be2dfc025436/model/model.py#L36

The good thing is that `//` is an explicit integer division in python 2 and 3, so making that replacement will not affect legacy support.

Cheers

**Comment by dylan-campbell** [comment]
Thanks Sérgio, good pick up!

PyTorch 1.5.1 and older did integer division for the / operator, but I believe this has since changed. I've replaced it with //.

Cheers,
Dylan

**Comment by SergioRAgostinho** [comment]
Closing with a55eb7684515ba4fa9ae9e0110500994b9f83175
