### ISSUE TITLE
Rotation error?

### ISSUE THREAD

**Issue by goodgoodliving** [dylan-campbell/bpnpnet#8]
I would like to ask why there is such a significant difference between the rotational error (°) results obtained when using the provided weight files in the "weights" folder for model testing and inference, compared to the values reported in the paper?

**Comment by goodgoodliving** [comment]
The results of rotational error (rot error) obtained through inference using the weight files are approximately in the range of 0.x, while the rotational error reported in the paper is generally greater than 1, considering the ModelNet40 dataset. I would like to know the reason behind this difference.

**Comment by goodgoodliving** [comment]
使用的参数文件是**.LCLP.pth.tar

**Comment by goodgoodliving** [comment]
The parameter file used is **.LCLP.pth.tar.

**Comment by dylan-campbell** [comment]
Hi @goodgoodliving, the paper reports rotation errors in degrees, while the code keeps everything in radians. Does this explain it?

**Comment by goodgoodliving** [comment]
> Hi @goodgoodliving, the paper reports rotation errors in degrees, while the code keeps everything in radians. Does this explain it?

Thank you for your response. I would like to ask about your previous article, "Learning 2D–3D Correspondences To Solve The Blind Perspective-n-Point Problem." I have also run the corresponding code using the provided parameter file for testing, and the result is approximately equal to 2. The result matches closely with what is stated in the paper, but there is a significant difference in the results from bpnpnet. Therefore, I have a few questions:

1. Is the measurement in "Learning 2D–3D" also in radians? If so, it seems unlikely that the corresponding rotation error would be so low in precision.

2. If the "Learning 2D–3D" code outputs the measurement in degrees, which seems more reasonable, does it imply that its performance is better than that of bpnpnet?

I look forward to your response.

**Comment by dylan-campbell** [comment]
Hi @goodgoodliving, yes, the results in both papers are in degrees.
1. No, I think the code for "Learning 2D–3D" converts the results into degrees.
2. Yes, it's performance is better. The BPnPNet architecture is quite vanilla, just with an interesting optimisation strategy, while "Learning 2D–3D" has several additional components that push the performance much higher.

**Comment by goodgoodliving** [comment]
> Hi @goodgoodliving, yes, the results in both papers are in degrees.
> 
> 1. No, I think the code for "Learning 2D–3D" converts the results into degrees.
> 2. Yes, it's performance is better. The BPnPNet architecture is quite vanilla, just with an interesting optimisation strategy, while "Learning 2D–3D" has several additional components that push the performance much higher.

Thank you very much for your patient and detailed response. You have resolved my doubts. I wish you all the best in everything.
